### ISSUE TITLE
xhr poll error on intranet domain

### ISSUE THREAD

**Issue by wortkrieg** [MarlBurroW/Streamdeck-Uptime-Kuma#1]
Hi there,

I tried to spin this up on our uptime kuma. Two things could be the problem:

- it runs on an intranet resource
- XHR header missing -> chromium blocking Request due to CORS policy.

When trying to connect to my domain http://uptime.xy.intranet/ in the PI, I get "xhr poll error". 

<img width="353" alt="PI-error" src="https://user-images.githubusercontent.com/35509013/210964791-0878a22c-98ea-4eb3-a343-653542dbf76b.png">

Having a look at the debugger I get:
<img width="670" alt="devtools" src="https://user-images.githubusercontent.com/35509013/210965540-f1037d31-346d-47a7-bb7b-e69e1d4d2374.png">

Let me know if more information required.

**Comment by MarlBurroW** [comment]
Can you test with `https://uptime.marlburrow.io` (with any credentials)
and tell me if you have the CORS error.
If you don't see `xhr poll error`, this is probably a server related issue that I need to investigate (CORS header not sent in the response).
In this case, give me the version of your Uptime Kuma (Docker tag of the image used).
Do you use a reverse proxy ?

**Comment by wortkrieg** [comment]
Hi there,

Updated plugin to 1.1.2, tested it with https://uptime.marlburrow.io, same result: xhr poll error. Should that work? If yes, then it could be me I guess.

I use the latest kuma version, tag is louislam/uptime-kuma:1 - last pulled 6 days ago. No reverse proxy.

**Comment by MarlBurroW** [comment]
Yes it should work, and you should see `authentication failed` like this:

![CleanShot 2023-01-09 at 11 34 10](https://user-images.githubusercontent.com/3024430/211288738-7620ece7-253b-4956-b657-bfb9636d87b2.gif)

It's obviously not server related, because you have the same error with my server.
I feel like your internal chromium version is different, what version of the Streamdeck software are you using ?
Here is mine: 
![CleanShot 2023-01-09 at 11 38 23](https://user-images.githubusercontent.com/3024430/211289457-ac011a5d-2275-425f-96da-d1958aa63335.png)

**Comment by MarlBurroW** [comment]
@louislam thank you very much for your reply.

I'm not able to reproduce on your instance, the socket request is allowed without any CORS restrictions like on mine.

I agree this is the expected behavior on an end-user browser, but I think the built-in Chromium instance integrated in the Streamdeck software have less CORS restrictions than classic browsers (probably to give more flexibility to developers)

Some users have reported some CORS issues on early major 6 of the Streamdeck Software.
See here: https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/cors_issue_since_upgrading_to_v6/

So my guess is @wortkrieg hasn't the latest version of the Streamdeck software (Hope so).

**Comment by wortkrieg** [comment]
Ok, updating stream deck software fixed the issue. Now I can connect to any instance without xhr failure. Shame on me for not checking my software version first. Good work, @MarlBurroW digging into reddit and finding this thread.

**Comment by MarlBurroW** [comment]
Thanks again for your report, I'll link this issue in the troubleshooting section (in README.md)

**Comment by dreadedhamish** [comment]
Just an FYI - OSX users using Mojave can't update to Stream Deck 6. Yes Mojave is outdated, initially being released in September 2018, but it's also the latest OSX that users of the also outdated cheesegrater Mac Pro's can upgrade to (without significant hacking).
